version: "3"
services:
  grpc-server:
    container_name: grpc-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
        - mynetwork
      
  grpc-client:
    container_name: grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - grpc-server
    networks: 
        - mynetwork

networks:
    mynetwork: